### PR TITLE
Speedups for several of the estimators

### LINKED ISSUE #103: There is a speedup possible for all predictors
P_local isn't required in most circumstances, so you can avoid a (possibly expensive) binary search. Take a look at comment 24 in our recent (v1.5) [90B comments.](https://bit.ly/UL90BCOM).

### LINKED ISSUE #105: The compression estimate could be considerably faster
When calculating the value of the compression estimates G function, at some point (generally quite early in the process) the intermediate values become so small they can't be distinguished from 0. At this point of the calculation, one can stop, as adding many copies of 0 to a sum does not change it.

In addition, you can control the accumulation of floating point error somewhat more efficiently by decreasing the number of additions. See our [implementation comments](https://bit.ly/UL90BCOM), in the new section "Compression Estimate G Function Calculation".

### LINKED ISSUE #106: The MultiMMC and LZ78Y predictors could be much faster with binary data
It's possible to deal with the binary case of these predictors without any advanced data structures, and the result is dramatically faster than when using these data structures. In this case, if we call the maximum substring length that we use as a prefix "A" (A=16 for both these predictors), the predictor only needs to be able to track (at most) 2^(A+2) counts. As such, you can just track all possible prefixes (rather than just the ones we encounter) with only modest memory use (2^21 bytes for the predictors here).

This approach does not work for wider data, as memory use grows exponentially with the number of symbols.

### PR DESCRIPTION
**Pull request by joshuaehill**
This implements a speedup noted in comment 24 of our recent (v1.5) [90B comments.](https://bit.ly/UL90BCOM).

This is intended to be applied after pull request #99.

Resolves #103 Resolves #105 Resolves #106.

### CODE REVIEW

**Comment by joshuaehill** [comment]
This pull request also includes a speedup for the compression estimate's G function.

**Comment by zrlsid** [comment]
There is currently a typo in the file compression_test.h at line 79 of this pull request. The line has to be commented out. With this fix I get the same results as with the master version.

**Comment by joshuaehill** [comment]
It's somewhat mysterious how I ended up introducing that; thanks for the report, I've updated the pull request. I'll also have some more changes for the MultiMMC prediction estimate and the LZ78Y prediction estimate within the next few days.

**Comment by celic** [comment]
Looks good so far. I will wait to merge this until you are ready.

**Comment by joshuaehill** [comment]
Good timing. I should be committing something today for the binary case. I also have code for the non-binary case, but it isn't ready yet.

**Comment by joshuaehill** [comment]
OK, I've now rebase'd the branch associated with this pull request against the new NIST master branch, so the list of commits should be accurate again.

**Comment by zrlsid** [comment]
I did a quick result comparison between previous LZ78Y implementation and the accelerated one from this pull-request. I've noticed a minor accuracy difference in the 1-bit prediction between the two versions. Is this expected and can we quantify this?

**Comment by joshuaehill** [comment]
There should be absolutely no significant difference whatever, and any variance in _some_ of these results is a bug (either in this code, or in the existing NIST code).

There are a few moving parts here; in verbose mode, the tool will report the parameters C and r; these are integer values that are wholly deterministic, and not subject to (compiler- and optimization-specific) floating point error accumulation differences.

What versions are you comparing? What data are you using that results in differences? Are these C and r values different between the two implementations?

**Comment by joshuaehill** [comment]
A difference in N is also a clear indication of a bug. I'll look into it, thanks!

**Comment by joshuaehill** [comment]
I neglected to correctly update the call to predictionEstimate() when I copied it from the MultiMMC predictor. This commit should fix it. Thanks again!

**Comment by celic** [comment]
@joshuaehill let me know when this is ready to merge. There's a lot of great improvements here.

**Comment by joshuaehill** [comment]
It's usable now. I do have some more work to do on the non-binary case of the MultiMMC and LZ78Y predictors, but that can wait (and doesn't really interact with this pull request).

Aaron Kaufer's improvements to the t-tuple and LRS estimators also look very interesting, and I'll integrate these in time as well.

**Pull request merged**
