### PR TITLE
A bunch of changes to fix the MultiMMC / LZ78Y predictors, and add self tests.

### PR DESCRIPTION
**Pull request by joshuaehill**
This pull request:
- Adds a new level of verbosity to support automated testing.
- Adds self tests.
- Harmonizes binary and non-binary implementations of MakeMMC and LZ78Y predictors.
- Corrects and speeds up wide MultiMMC and LZ78Y predictors.
- Makes file IO more robust, and adds logic to generate or validate the symbol width.
- Adds command line option to load subset of large files.
- Trys to make the calculation and reporting of H_bitstring and H_original consistent.
- Reduces epsilon to reflect the most accurate reasonable value.
- Adds binary test data, and attempted to reduce overlap in existing data.
- Fixes typo in the LRS memset call.

After making these changes, I ran our internal regression tests (over 5000 invocations of of the assessment code on a variety of different simulated sources) using the NIST ea_non_iid binary, and found that the results were broadly consistent with the results of our internal tool (a relative difference of no more than 6.0E-8). This is certainly the largest scale testing that I've done of this tool, and it may be the largest scale testing of this tool to date.

Resolves usnistgov/SP800-90B_EntropyAssessment#94.
Resolves usnistgov/SP800-90B_EntropyAssessment#114.
Resolves usnistgov/SP800-90B_EntropyAssessment#115.
Resolves usnistgov/SP800-90B_EntropyAssessment#116.
Resolves usnistgov/SP800-90B_EntropyAssessment#117
Resolves usnistgov/SP800-90B_EntropyAssessment#119
Resolves usnistgov/SP800-90B_EntropyAssessment#121
Resolves usnistgov/SP800-90B_EntropyAssessment#122

### CODE REVIEW

**Comment by joshuaehill** [comment]
As an aside, the selftest functionality requires perl.

**Comment by joshuaehill** [comment]
I just fixed some additional bug fixes that seemed to affect certain error conditions.

**Comment by joshuaehill** [comment]
I noticed bunch of inconsistencies between the README file and the current command line structure, and tried to make everything accurate and consistent. I also noticed that the processing performed in ea_iid wasn't consistent with the processing done in ea_non_iid. I altered the processing of ea_iid to be consistent with the procedure described in 90B.

**Comment by joshuaehill** [comment]
These most recent changes bring the maximum result difference between the NIST reference and internal UL tool down to less than 2.0E-11.

**Comment by joshuaehill** [comment]
I just added ea_transpose to this branch, so this pull request will also resolve issue #121.

**Comment by celic** [comment]
The 5k sample is definitely the largest performance evaluation of this tool. Certainly more than any iterations I've done myself (on the scale of 50ish). Thank you for the work. This is a larger PR, so I'll need some time to review it. With ICMC as well it likely won't be until after. I will get to it before 5/23.

**Comment by celic** [comment]
This is great. Some minor changes to the Makefile were needed to compile on OSX, but everything runs very smoothly (and incredibly fast!).

**Pull request merged**
