### PR TITLE
Modified to use packed data, enhance verbose output, increase efficie…

### PR DESCRIPTION
**Pull request by zipnemud**
…ncy of permutation check

Lots of changes here.

I increased the verbose output in permutation_tests.py.  It's now possible to monitor what is happening as the permutation tests are run.

I changed the tests in permutation_tests.py so that when the pass criteria are met, the test ends.  I changed the tests in permutation_tests.py so that when a test has passed, it no longer is computed.  These two changes mean that the permutation tests are *much* faster.

I increased the output of restart.py under verbose.

I altered the row and column frequency selection in restart.py so that the results are saved in case future analysis is desired.

I changed to_data in util90b.py so that packed data is used.  This allows bit sizes of greater than 8 bits, but their use is curtailed because the rest of the programs don't deal well with the larger size.  I did get a 9 bit sample size to pass the restart tests.

I added two new variables to the arguments list in the parser in util90b.py.  They are a start_position and read_amount.  The start_position is where to start reading random data in the file, and the read_amount is how many bytes to read.  This allows a larger file to be processed in chunks, so that restart can still be run on the output.

I modified iid_main.py, noniid_main.py, and restart.py to utilize the start_position and read_amount parameters.

### CODE REVIEW

**Comment by joshuaehill** [comment]
Short circuiting when the failure conditions of the permutation tests can't be met is a nice refinement.
 
One comment: your code will do one more test round than it needs to, as you don't check to see if the post-incremented values result in a pass prior to setting the pass_flag to False. You should re-check to see if the conditions are met after incrementing the C_{i,0} and C_{i,1} variables (line 563 in your permutation_tests.py file).

**Comment by joshuaehill** [comment]
I implemented the "early finish" idea described here, and was able to characterize the degree of speedup with iid data. In particular, I ran a bit over 10,000 perm tests on pseudo-random (CTR_DRBG output) data; this output data was treated this as a bit source, so these results are only directly applicable to the bit-oriented variants of these tests.

I characterized the number of data permutations required until the permutation test could be judged as passing. After 10,757 permutation tests, the sample median was 279 permutations until passing, and the sample mean was 834.5 permutations until passing. The corresponding histogram is:
short-circuit-perm-round-dist

The summary is that (for fairly ideal data), you get over an order of magnitude advantage in data permutations required by checking to see if you can stop early. Further, if you stop performing individual tests when you have already satisfied their passing criteria, the actual speedup is even better than suggested by this data.

**Comment by zipnemud** [comment]
Sorry for the late response, I thought I would get notified when you commented.  This is in response to your first comment, about changing the logic for the pass flag.

I think that altering the logic to do what you want would be more expensive than leaving it as is.  I had to think about it, though.  :-)  

The last pass will perform no permutation tests, because each individual test is guarded, it will only cycle through all the tests again to confirm that they all pass.

But adding the check to determine if the test has passed after the increments will be done for each permutation test on each cycle until it has passed.  

To me, this seems more expensive than just doing the extra round.

On another note, your graph of the test you ran was very nicely done.  I'm a bit surprised that the failure rate is so high, though; it looks like it is around 2 percent.

**Comment by zipnemud** [comment]
PS  Yes, the short circuit is nice, but it is only possible because we aren't keeping the permutation test results from each trial, in order to check their distribution.  e.g.  You rerun your 10000+ tests, but keep a record of the result for each permutation test for each run (no short circuit).  Then look at the distribution of the results for each permutation test from the 10000+ trials.

I think that would be a more valid test of the generator, but, of course, it would be time consuming to do that.

**Comment by joshuaehill** [comment]
I agree that you get better data about the test, itself, by collecting all the data. In my version, I added a command line flag to force all the permutations to occur, which would allow you to assess how the distribution of percentiles is for each test (one would like this distribution to be roughly uniform for random data). This would allow you to verify that the test is reasonably well constructed. Prior testing of this sort that I've done suggests that the permutation tests are mostly reasonably constructed. (The percentile distribution ended up being mostly uniform, but with a few spikes that didn't obviously increase the chance of a type 1 error for the tests).

I caught a bug in my "early exit" code that inappropriately allowed one of the tests to fail without exhausting all 10000 rounds; I'll retest given this change, and post an updated histogram.

Each test has a 1/1000 chance of failure; if we assume that these are independent (which is a strange assumption, even if the input _is_ random), then we'd expect a failure rate of 1-(999/1000)^11, which is about a 1% failure rate. After I retry the testing, we'll see how that compares.

As a side issue, for testing the iid hypothesis on binary data, take a look at issues #28 and #29; these test construction issues significantly impact the assessment. I haven't spent much time looking at the details of the non-binary case, so I can't meaningfully comment on the performance of those tests.

**Comment by zipnemud** [comment]
The fact that known random data displays a uniform distribution to these tests makes me feel better about them.   I can happily use the short cut.

Shouldn't the non-binary case align with the binary case regarding entropy content?  If there is entropy present in the input, it should be there regardless of the sample size (given enough input, obviously).  I guess I'm arguing that if the binary case shows that each bit has entropy close to 1 (I get ~.995), it can't disappear at larger sample sizes;  if it did, I would be leery of accepting the results of the binary tests.  My thinking is that a random generator is a random generator, no matter how its output is cut, sliced, and diced, as long as it is done in a non selective manner.  In my tests, I've found that all sizes from 1 to 7 bits pass on the same data, as I would expect.  I have had a problem with 8 bits, as they pass the iid_main test, but always seem to fail the sanity check.  Because of the above logic, I presumed that the problem was with the 8 bit sanity check, and not with the data.

**Comment by joshuaehill** [comment]
Also, in response to your "it shouldn't matter how you slice and dice" comment: It's important to recognize that this entire test suite is for operating on raw noise data, which will generally have a particular width to it. If you're grabbing from an n-bit ADC, then the noise source samples should be passed in in n-bit samples. Similarly, if your noise source is fundamentally bit-oriented (e.g., a ring oscillator), the data should be passed in a bit at a time (in the order the bits were produced). There are situations where you need to map the data down, but each mapping is likely going to induce different behavior and get a different assessment.

**Comment by zipnemud** [comment]
I agree with you on the first part, that's just a convenience issue.  But I think I disagree with your last statement, depending on how you meant it; my perspective is that as long as the mapping is unbiased, the result better be the same as the result from the unmapped data, or the stream isn't random.  e.g. if I am receiving 4 bit data, and I take the third bit of every sample, aggregate those bits into 8 bit bytes, accumulate 1 million of them, and run the 8 bit test on the result, it should get the same result as if I ran the test on the 4 bit data directly over the same 32 MB of data.  Or, if I pair two 4 bit samples into a byte and accumulate a million bytes, the result of 8 bit testing should be the same as if I ran two tests at 4 bits on the same data.

Or, another way to put it is that random data streams have no implicit biases.  That's what we're trying to establish with the tests; if the data stream is reduced to a stream of bits, then the probability of the next bit being a 1 is always .5 for random data.  If that is true, then like a fractal, whatever level of aggregation or mapping is done to the data, as long as it is unbiased, it, too, will be random.

The caveat is that random data streams can produce non random sequences, so the tests will appear to fail occasionally even for random streams.  Thus the need to run the different mappings on the same data.

**Comment by joshuaehill** [comment]
The iid tests don't look for bias at all (that is, some symbols are allowed to occur more frequently than others). They should pass with highly biased (but iid) data. Indeed, in my testing, this appears to be so.

I agree that mapping down from larger to smaller symbols (and discarding the rest) should not introduce a correlation (this procedure may well mask a correlation), but splitting up a large sample to smaller samples could lead to the iid tests failing when they ought not, and packing distinct samples into one sample could lead to the iid tests passing when they ought not.

Some toy examples: If we have a source that produces  6-bit iid data, whose 4th bit is always equal to its first bit, then the tests should pass when you pass the data in 6 bits at a time. If you split this 6-bit sample into two three bit samples, then the tests should _not_ pass the iid tests, because there is a correlation between the low order bits of adjacent three-bit samples.

Similarly, if you have a bit-oriented source which produces non-iid data (due to a similar correlation between bits every third bit) the iid tests should fail, but if you package the data into 6 bit chunks (such that the only correlation is within individual samples), then you would expect the iid test to pass.

The end result is that (much like the non-iid case) it is vital to convey information to the tests one "natural sample" at a time.

**Comment by zipnemud** [comment]
Interesting.  Thanks for the explanation.  I had just assumed that iid was a synonym for random.  I can see that your arguments are true, but why would we care?  What good is knowing an entropy estimate for non random generators?  If I want non random data, I can always create it to order from random data.  And I wouldn't want to feed non random data into any kind of PRNG.  It's not like true RNGs aren't available, https://en.wikipedia.org/wiki/Comparison_of_hardware_random_number_generators.  I must be missing something, because you obviously went to a lot of effort to build this, and you wouldn't have unless there was a purpose.

At least I now understand why to_dataset functions the way it does in the original utility.  I wondered why it was designed that way if you were testing RNGs, but it is clear it has to be for your purposes.

**Comment by kerrymckay** [comment]
An entropy source is not a random bit generator, but just one component of a random bit generator. Entropy sources do generate random data, but the randomness can be drawn from many probability distributions, not necessarily from the ideal case of the uniform distribution. Entropy source outputs are used as inputs for other algorithms (e.g., see the DRBGs in SP 800-90A, http://doi.org/10.6028/NIST.SP.800-90Ar1 ) to form non-deterministic random bit generators (or as the rest of the world calls them, true random number generators). NIST will be providing guidance in SP 800-90C on how to put the pieces from 90A and 90B together to make different kinds of random bit generators.

**Comment by zipnemud** [comment]
Thanks for your response.  Being pedantic, I think I disagree partly with the statement "An entropy source is not a random bit generator"; an entropy source *can, but doesn't have to,* be a random bit generator.  e.g.  If I have a neutrino detector and create a zero area and an equal one area, and define a neutrino passing through the zero area as a zero, and a neutrino passing through the one area as a one, this is a random bit generator through time.  I suppose if *you* want to be pedantic, the detection could be considered an algorithm that converts the neutrino events into a bit stream, and your statement becomes valid.  To get digital output from an analog process will always require some sort of measurement, and all randomness in this universe is analog.  Splitting hairs, but I think this is a procedure rather than an algorithm, https://www.quora.com/What-is-the-difference-between-an-algorithm-and-a-procedure

Sure, random output is used to seed PRNGs, but the important component of that randomness is that it be unpredictable.  Suppose we want a 128 bit key value.  Every 128 bit key value is a random value, since by definition, every 128 bit value can come from a random bit generator.  If I say 'zero' or 'one' in as random an order as I can until I have 128 bits, that is random (could you reproduce such a string on demand?), and a perfectly valid way to seed a PRNG.  It is certainly unpredictable, even by me, unless I make an effort to introduce some sort of pattern.  So, of course we can use the output of any biased distribution to seed a PRNG.  If we have several such generators that are biased, keep them secret, and choose one by flipping a coin when we want to reseed, they will work just fine as seeds, because the coin flip (and reseed timing) provides the unpredictability over time that thwarts analysis of the PRNG output to determine the key.

I look forward to reading SP 800-90C to see your guidance for that process of generating random seeds from biased distributions.  If such a process is going to be effective, I think it will have to somehow map those biased distributions into a uniform distribution, or at least an approximation of one.

**Comment by joshuaehill** [comment]
This software is a reference implementation for the testing required in the 2016 draft of NIST SP800-90B. If you want to know how the eventual SP800-90{A,B,C} documents are likely going to work, you could review the most recent drafts of these documents (though, as NIST has been pointing out for a year or so, the final versions of these documents are expected to be published "soon"). The term "entropy source", "DRBG", and related terms are defined there. As this code is intended to perform the tests in this document, the meaning of the terms used here are consistent with those documents' definitions. 

The procedure for conditioning non-uniform (and indeed, non-iid) distributions are already described in the current draft of SP800-90B, though this process is optional. Within this scheme, an entropy source is used to provide entropy to an approved DRBG (SP800-90A), or to support one of the NRBG designs in SP800-90C.

By reviewing all of these documents (at least at a high level), I think you'll find that the current conceptualization of how these parts fit together is basically reasonable, and the terminology used is already broadly established.

**Comment by joshuaehill** [comment]
As a follow on to my prior statement, SP800-90B final has now been [released](https://csrc.nist.gov/publications/detail/sp/800-90B/final).

**Comment by joshuaehill** [comment]
Following up on my prior post providing a distribution, I have some graphs to share, which reflect the results of 5402 permutations for each data width that I examined.

For 1-bit values, the median is 299 rounds, and a histogram of the number of rounds required is:
permtest-1-bit-rounds

For 3-bit values, the median is 276 rounds,a histogram of the number of rounds required is:
permtest-3-bit-rounds

For 8-bit values, the median is 307 rounds,a histogram of the number of rounds required is:
permtest-8-bit-rounds

For 10-bit values, the median is 302.5 rounds, a histogram of the number of rounds required is:
permtest-10-bit-rounds

For 16-bit values, the median is 294 rounds, a histogram of the number of rounds required is:
permtest-16-bit-rounds

To address the fail rate as compared to sample size, we have the following graph:
permtest-passrate

In this last graph, the horizontal lines show the expected failure rates (if we consider each of the 19 permutation tests as independent), if the underlying failure rate for each permutation test is 1/1000 (lower horizontal line) or 2/1000 (upper horizontal line).

**Pull request closed without merging**
