### PR TITLE
Uncommented stderr debugging stmt

### PR DESCRIPTION
**Pull request by mclearn**
Just a small presentation issue. In binary_chi_square_independence, there was an uncommented stderr output debugging statement.

### CODE REVIEW

**Comment by joshuaehill** [comment]
I suspect that's my fault. I noticed one other instance where this would come up in normal testing: ``fprintf(stderr, "LRS Estimate: v<u. Can't Run LRS Test.\n");``
in cpp/shared/lrs_test.h. Two options: 
1. you could move this additional fprintf over to a printf in your existing pull request, or 
2. I could integrate both changes into an existing pull request, and you could close your pull request.

Either works for me. Let me know what you'd prefer.

**Comment by mclearn** [comment]
I updated the other fprintf to be a printf gated behind a verbosity check.

**Comment by mclearn** [comment]
Sorry about that.  I accidentally added some new presentation material to this merge request.  Reverted and will branch for the new bit.

**Comment by joshuaehill** [comment]
That message should really occur even when not in verbose mode. It's a condition that results in no information from the LRS test.

**Comment by joshuaehill** [comment]
Also, for the permutation testing, it would be useful to indicate what percentage of the tests have passed, as there are two ways to finish permutation testing (either do the full 10000 rounds of it, or passing all the tests).

**Comment by mclearn** [comment]
Thanks.  I literally have some code in a local branch to do this but it is complicated by the threading model as to the best way to present it.  I can make it look nice for a single thread, but multiple threads are messy.

~greg
(613) 979-3775

**Comment by joshuaehill** [comment]
It's not the best idea to do this testing single-threaded. :-)

**Comment by mclearn** [comment]
... and fixed up printf stmt.

**Pull request merged**
