### PR TITLE
Allow permtesting large data sets, command line processing fixes.

### PR DESCRIPTION
**Pull request by joshuaehill**
This seems to be a general issue for all large data sets. This pull request converts the data storage in permutation testing to dynamic allocations, and addresses at least one problem with large data sets.

I think that this closes issue #97 , closes issue #66, closes issue #100, closes issue #101, closes issue #102.

### CODE REVIEW

**Comment by joshuaehill** [comment]
I handled one additional corner case (comparison between two values whose delta causes an overflow) and expanded comments in relEpsilonEqual(). This shouldn't change anything at all, as the case I handled shouldn't naturally arise in testing within this tool.

**Comment by dpiegdon** [comment]
this branch fixed the segfault for me. dataset was ~16MByte. thanks!

**Comment by joshuaehill** [comment]
Thanks for the report!

**Comment by joshuaehill** [comment]
I updated this pull request to deal with the outstanding command line parsing issues as well.

**Comment by joshuaehill** [comment]
The pull request was updated to document the new ordering of command line parameters (which is apparently enforced on some implementations of getopt). Thanks to @zrlsid for pointing out this issue!

**Comment by zrlsid** [comment]
Thank you! I actually switch to this pull request, because I was experiencing segfaults as well. However, your update solves it.

**Comment by celic** [comment]
Thank you @joshuaehill for the great work!

**Pull request merged**
