### PR TITLE
Inconsistent variable with usage

### PR DESCRIPTION
**Pull request by Zalamar**
Mix between using FileLength and FileLen breaking the compilation, just changed all to FileLen.

### CODE REVIEW

**Comment by joshuaehill** [comment]
I reviewed the change, and don't see any reason why the original code should have caused a problem. (More to the point, the changes you made shouldn't change anything after compilation). What compiler are you using, and what was its error message?

**Comment by joshuaehill** [comment]
I added a PR that addresses all of the bugs that I saw in the `sha256_file()` function, including the one fixed in this PR.

@celic If you merge PR #204, you don't need to merge this PR.

**Comment by andrewmccaffreynist** [comment]
Not merged as the fixes were incorporated/superseded by #204

**Comment by joshuaehill** [comment]
@andrewmccaffreynist I think that this PR can be closed.

**Pull request closed without merging**
