### PR TITLE
Support large files and fix an initialization problem

### PR DESCRIPTION
**Pull request by joshuaehill**
* Add support for datasets with large number of samples files. (> 2GS).
   * Requires divsufsort64 (generally included in the relevant package).
* Resolved initialization error in ea_conditioning.

### CODE REVIEW

**Comment by joshuaehill** [comment]
This is mainly useful because it allows for more samples of wide data; this comes up most frequently with the bitstring tests. For the 8-bit data, the prior code would fail with 8-bit data that was larger than about 256MB.

**Comment by celic** [comment]
The changes look fine but we need to do some testing with this to ensure that including the new `-ldivsufsort64` library doesn't affect our ESVTS build process. Are both libraries needed? Or can we remove the `-ldivsufsort` now?

**Comment by joshuaehill** [comment]
Both libraries are required when linking. The tool opportunistically uses the 32-bit version of the tool when it can, because the 32-bit version of the library uses literally half the memory of the 64-bit version.

**Comment by celic** [comment]
The math checks out on that one. I'll test this out on an internal ESV environment to ensure it doesn't break anything before I merge it in.

**Pull request closed without merging**
