### PR TITLE
Make ea_conditioning use arbitrary precision arithmetic (and only that)

### LINKED ISSUE #128: "double" and "long double" precision may not be sufficient within conditioning_main
Within the CMUF Entropy WG, we are presently discussing the definition of "full entropy" with respect to SP800-90A/SP800-90B. One proposed definition effectively comes from the 2012 draft of the SP800-90B document, and looks like this:

> An n-bit string is said to provide full entropy if it is obtained through a process that is estimated to provide at least (1 - ε)n bits of min entropy, where 0 <= ε<= 2^(-64).

To determine if such a definition is fulfilled, we need to calculate ε, where h_out = (1 - ε)n_out, so log(ε) = log(1 -(h_out/n_out)), and verify that - log(1 - h_out/n_out) / log(2) >= 64.

Sadly, for double arithmetic, the best case accuracy (DBL_EPSILON) is only 2^-52. If we moved to long double arithmetic, we gain a bit and arrive at LDBL_EPSILON = 2^-63. Neither is sufficient to this task, and indeed if I compare the output of the ea_conditioning tool with the output of a computer algebra system (using arbitrary precision floating point calculations), I find significant precision problems from ea_conditioning when it's output is close to full entropy.

If the definition of "full entropy" goes this way, the floating point calculations within conditioning_main will need to be conducted using an arbitrary precision floating point library of some sort.

I'll do some testing using the MPFR library and see how it goes.

### PR DESCRIPTION
**Pull request by joshuaehill**
Makes conditioning_main.cpp use arbitrary precision floating point (and only that). The same as #129, but without the documentation fixes (which will now be in pull request #137).

Makes conditioner render verdict with respect to the 2012 SP800-90B draft's definition of 'full entropy'; the use of the definition from this document is well marked: the tool's output message is "SP800-90B 2012 Full Entropy", so irrespective of how the final definition goes, this PR is still reasonable.

Our discussions with the SP800-90B authors at the CMUF Entropy Working Group indicate that the NIST authors intend a definition that is at least conceptually related to the one described here.

Resolves #128

### CODE REVIEW

**Comment by joshuaehill** [comment]
Barring some feedback from the 90B authors, it seems likely that this definition is being dropped from the CMUF Entropy WG's proposed SP800-90B FIPS 140-2 IG. This code is still quite useful for making sense of the calculated entropy (when it is near full entropy), so I still suggest merging this PR.

**Comment by celic** [comment]
I'd like to talk to the authors on 90B a bit on the definition. If it is indeed useful to include this code, it may need to be framed in such a way to not be confused with the 90B definition. 

I'll track down the IG as well just to make sure things are consistent.

**Comment by joshuaehill** [comment]
I just updated this PR so that it now reports results with respect to the 2021 SP 800-90C draft's definition of "full entropy", and reports all the parameters that seem like they ought to be reported.

I still think that this is a useful PR, and suggest that it be merged. In the event that it is not merged, I would suggest looking at the information output and modifying the base tool to also output this information. (That said, you should note that reporting the `-log_2(epsilon)` values is not likely to work without some sort of arbitrary precision library).

**Comment by joshuaehill** [comment]
To highlight some advantages of this output, this version detects the "very close" condition to each of the limiting variables (`h_in`, `nw`, and `n_out`). Here is run that shows how "closeness" to `h_in` is shown (this would generally be reported as `h_out = h_in`,  but this condition that never quite happens):
```
ea_conditioning -v 512 128 128 64
n_in = 512
n_out = 128
nw = 128
h_in = 64
Output_Entropy(*) = 64; Close to h_in (epsilon = 69.47123362705510238312)
(Vetted) h_out = 64
```

Here is a version that is, in some sense, "close" to full entropy, but not quite:
```
ea_conditioning -v 512 128 128 150
n_in = 512
n_out = 128
nw = 128
h_in = 150
Output_Entropy(*) = 127.9999996560347392815
(Vetted) h_out = 127.9999996560347392815
epsilon = 2^(-28.47123379903773616322)
```

But if you increase the entropy input just a bit then...
```
ea_conditioning -v 512 128 128 155
n_in = 512
n_out = 128
nw = 128
h_in = 155
Output_Entropy(*) = 127.9999999892510843604
(Vetted) h_out = 127.9999999892510843604
epsilon = 2^(-33.47123363242956020635): SP 800-90C 2021 Full Entropy
```

This code still identifies compliance to the 2012 SP 800-90B draft's definition of "full entropy":
```
ea_conditioning -v 512 128 128 190
n_in = 512
n_out = 128
nw = 128
h_in = 190
Output_Entropy(*) = 128; Close to n_out (epsilon = 68.47123362705510238312); Close to nw (epsilon = 68.47123362705510238312)
(Vetted) h_out = 128
epsilon = 2^(-68.47123362705510238312): SP 800-90B 2012 Draft and SP 800-90C 2021 Draft Full Entropy
```

Finally, this version makes reporting all the relevant parameters much easier for non-vetted conditioning functions:
```
./ea_conditioning -n 512 128 128 190 0.96
n_in = 512
n_out = 128
nw = 128
h_in = 190
h' = 0.9599999999999999999804
Output_Entropy(*) = 128; Close to n_out (epsilon = 68.47123362705510238312); Close to nw (epsilon = 68.47123362705510238312)
0.999 * n_out = 127.8719999999999999973
h' * n_out = 122.8799999999999999975
(Non-vetted) h_out = 122.8799999999999999975
```

**Comment by celic** [comment]
Ending up with 

```
g++ -std=c++11 -fopenmp -O2 -msse2 -ffloat-store -march=native  conditioning_main.cpp -o ea_conditioning -lmpfr -lgmp
conditioning_main.cpp:10:10: fatal error: mpfr.h: No such file or directory
 #include <mpfr.h>
          ^~~~~~~~
```

while compiling. Where are you getting the multi-precision library from?

**Comment by joshuaehill** [comment]
I had to separately install a separate library (the GNU MPFR library). In my particular case (Ubuntu 18), I'm getting it from a package called libmpfr6(-dev). On my system, this is installed using a command like
``
sudo apt-get install libmpfr-dev libmpfr6
``

Let me know if you have any additional questions!

**Comment by joshuaehill** [comment]
The library `libmpc` is for arbitrary-precision complex numbers (this library also relies on GNU MPFR). We don't use complex numbers in this PR, so you shouldn't need `libmpc`.

GNU MPFR uses GNU GMP, and that dependency should be automatically dealt with when installing `libmpfr`.

**Comment by celic** [comment]
I'll try these specific packages, I believe they were included in the full `libmpc` install.

**Comment by celic** [comment]
It appears that only `sudo apt-get install libmpfr-dev` is needed for the header file. What does `libmpfr6` provide? Just a compiled version?

**Comment by joshuaehill** [comment]
Many(/most?) package systems break up the binary library (required for already compiled programs) and the files required for development using that library into two packages. libmpfr-dev is the package that supplies the files for development.  You likely already installed the libmpfr6 package (or some other package fulfilling the same dependency) automatically when you installed libmpc.

**Pull request merged**
