### PR TITLE
First round of permutation test fixes

### LINKED ISSUE #61: Some of the iid permutation tests are not invariant under translation
The translation that is used retains relative ordering, but nothing else. Some of the results of the permutation tests have different results when applied to translated or non-translated data. As such, these tests should be applied to the original data, not the translated data.

The Excursion test statistic (SP800-90B section 5.1.1), covariance test statistic (SP800-90B section 5.1.10), and compression test (SP800-90B section 5.1.11) aren't invariant under translation, so it's not clear that it's appropriate to use a translated version of the data set for these tests.

_Merged with duplicate issue #76 ._

### LINKED ISSUE #78: Calculation of number of runs is off by 1
The approach that the NIST tools uses for counting runs only counts transitions between symbols. This results in under counting the number of runs.

As an example, the run count for the string "0 0 0 0" is 1, not 0 (as "0 0 0 0" is a run of 0s).

This appears to happen across all permutation tests where runs are counted.

### LINKED ISSUE #79: The compression permutation test returns nonsense
There are a few issues here.

First, the use of the resize() method doesn't do what you want it to (the current use seems to presume that it just pre-allocates a bunch of memory). When you call "resize" in this way, it appends null characters to the string, until it is as long as you specify (strings in C++ are allowed to contain NULL characters!) When you then append values to the string, they are added _after_ the NULL characters that you added. So, when you access the string using the c_str method and then extract the length of the string using strlen(), you get 0 (as this string starts with NULL characters). As a consequence, you're just asking the BZ2 function to compress an empty string.

Next, the output buffer is not adequately large for most data sets (all datasets with more than 10 symbols would have problems.) The bz2 library manual indicates that this buffer should be at least 1% larger than the input size, plus 600.  (http://linux.math.tifr.res.in/manuals/html/manual_3.html#SEC36)

### LINKED ISSUE #82: Median is calculated incorrectly
The median calculation presumes that there are an even number of symbols.

The median is supposed to be set to 0.5 for binary data (though this may not, in fact, be the sample median...)

### PR DESCRIPTION
**Pull request by joshuaehill**
This pull request resolves an "off by 1" problem for counting runs and a couple of problems in the compression permutation test (a string construction problem and a buffer length problem).

I'm still seeing mismatches in the tests that aren't invariant under translation, so that problem could also be masking other problems.

As of Oct 1, this pull request Closes #78, closes #79, closes #82, closes #61.

### CODE REVIEW

**Comment by joshuaehill** [comment]
At this point, I think that this pull request closes all the permutation issues that I currently know about.

**Comment by celic** [comment]
Hi Josh, I'm going through the PRs and this one has some conflicts. Would you be able to take a look when you have a chance?

**Comment by joshuaehill** [comment]
Sure, I'll take a look this evening.

**Comment by joshuaehill** [comment]
OK, I rebased off the current NIST master branch, and then fixed the merge issues. This pull request should merge cleanly now...

**Pull request merged**
